name: 🧠 Generate GitHub Metrics

on:
  schedule: [{cron: "0 0 * * *"}]  # Every day at midnight
  push: {branches: ["main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Vivekkk-1
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
