name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Vivekkk-1
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      # Step 3: Push the generated files back to the repository
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "Vivek Snake Bot"
          author_email: "vivek@snake.bot"
          message: "Generated snake animation"
          add: "dist/*.svg dist/*.gif"
